[package]
name = "rust-px4-drv-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../protocol" }
rusb = "0.9"
thiserror = "1"
anyhow = "1"
crossbeam-channel = "0.5"
ctrlc = "3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "time"] }
time = { version = "0.3", features = ["local-offset"] }
clap = { version = "4.4", features = ["derive"] }
socket2 = "0.5"